blank_issues_enabled: false
contact_links:
  - name: ⚠️ NO SUPPORT PROVIDED - READ THIS FIRST
    url: https://github.com/trippixn963/QuranBot#-no-support-policy
    about: "🚨 CRITICAL: This project is provided AS-IS with ZERO SUPPORT. No bug reports, feature requests, or assistance will be provided."
  - name: 📖 Project Documentation
    url: https://github.com/trippixn963/QuranBot#-quick-start
    about: "Read the complete setup guide and documentation before using the project."
  - name: 🔧 Configuration Help
    url: https://github.com/trippixn963/QuranBot#-configuration
    about: "Learn how to configure the bot properly for your Discord server."
  - name: 🕌 Islamic Resources
    url: https://github.com/trippixn963/QuranBot#-features
    about: "Understand the features and Islamic context of this Quran streaming bot."
